package com.iAcon.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.iAcon.database.model.BindWardBean;
import com.iAcon.database.model.fetchmsg;
import com.iAcon.database.model.jianhu;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jianhuDaoConfig;
    private final DaoConfig fetchmsgDaoConfig;
    private final DaoConfig bindWardBeanDaoConfig;

    private final jianhuDao jianhuDao;
    private final fetchmsgDao fetchmsgDao;
    private final BindWardBeanDao bindWardBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jianhuDaoConfig = daoConfigMap.get(jianhuDao.class).clone();
        jianhuDaoConfig.initIdentityScope(type);

        fetchmsgDaoConfig = daoConfigMap.get(fetchmsgDao.class).clone();
        fetchmsgDaoConfig.initIdentityScope(type);

        bindWardBeanDaoConfig = daoConfigMap.get(BindWardBeanDao.class).clone();
        bindWardBeanDaoConfig.initIdentityScope(type);

        jianhuDao = new jianhuDao(jianhuDaoConfig, this);
        fetchmsgDao = new fetchmsgDao(fetchmsgDaoConfig, this);
        bindWardBeanDao = new BindWardBeanDao(bindWardBeanDaoConfig, this);

        registerDao(jianhu.class, jianhuDao);
        registerDao(fetchmsg.class, fetchmsgDao);
        registerDao(BindWardBean.class, bindWardBeanDao);
    }
    
    public void clear() {
        jianhuDaoConfig.getIdentityScope().clear();
        fetchmsgDaoConfig.getIdentityScope().clear();
        bindWardBeanDaoConfig.getIdentityScope().clear();
    }

    public jianhuDao getJianhuDao() {
        return jianhuDao;
    }

    public fetchmsgDao getFetchmsgDao() {
        return fetchmsgDao;
    }

    public BindWardBeanDao getBindWardBeanDao() {
        return bindWardBeanDao;
    }

}
