package com.iAcon.database.model;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BIND_WARD_BEAN.
 */
public class BindWardBean implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
    private String ward_name;
    private Integer ward_id;
    private Integer releaseSOS;
    private String status;
    private String watch_tel_no;
    private Integer guard_identity;

    private String user_id;
    
    public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public BindWardBean() {
    }

    public BindWardBean(Long id) {
        this.id = id;
    }

    public BindWardBean(Long id, String ward_name, Integer ward_id, Integer releaseSOS, String status, String watch_tel_no, String user_id, Integer guard_identity) {
        this.id = id;
        this.ward_name = ward_name;
        this.ward_id = ward_id;
        this.releaseSOS = releaseSOS;
        this.status = status;
        this.watch_tel_no = watch_tel_no;
        this.user_id = user_id;
        this.guard_identity = guard_identity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWard_name() {
        return ward_name;
    }

    public void setWard_name(String ward_name) {
        this.ward_name = ward_name;
    }

    public Integer getWard_id() {
        return ward_id;
    }

    public void setWard_id(Integer ward_id) {
        this.ward_id = ward_id;
    }

    public Integer getReleaseSOS() {
           return releaseSOS == null?0:releaseSOS;
    }

    public void setReleaseSOS(Integer releaseSOS) {
        this.releaseSOS = releaseSOS;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getWatch_tel_no() {
        return watch_tel_no;
    }

    public void setWatch_tel_no(String watch_tel_no) {
        this.watch_tel_no = watch_tel_no;
    }

    public Integer getGuard_identity() {
        return guard_identity;
    }

    public void setGuard_identity(Integer guard_identity) {
        this.guard_identity = guard_identity;
    }

    int to_type = 2;

	public int getTo_type() {
		return to_type;
	}

	public void setTo_type(int to_type) {
		this.to_type = to_type;
	}

	String type;

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
