package com.iAcon.database.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FETCHMSG.
 */
public class fetchmsg {

    private Long id;
    private Long msg_id;
    private Integer from_id;
    private String from_name;
    private Integer from_type;
    private String to_id;
    private Integer msg_type;
    private Integer msg_status;
    private String msg_content;
    private String create_time;
    private String ward_id;
    private Integer type;

    public fetchmsg() {
    }

    public fetchmsg(Long id) {
        this.id = id;
    }

    public fetchmsg(Long id, Long msg_id, Integer from_id, String from_name, Integer from_type, String to_id, Integer msg_type, Integer msg_status, String msg_content, String create_time, String ward_id, Integer type) {
        this.id = id;
        this.msg_id = msg_id;
        this.from_id = from_id;
        this.from_name = from_name;
        this.from_type = from_type;
        this.to_id = to_id;
        this.msg_type = msg_type;
        this.msg_status = msg_status;
        this.msg_content = msg_content;
        this.create_time = create_time;
        this.ward_id = ward_id;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMsg_id() {
        return msg_id;
    }

    public void setMsg_id(Long msg_id) {
        this.msg_id = msg_id;
    }

    public Integer getFrom_id() {
        return from_id;
    }

    public void setFrom_id(Integer from_id) {
        this.from_id = from_id;
    }

    public String getFrom_name() {
        return from_name;
    }

    public void setFrom_name(String from_name) {
        this.from_name = from_name;
    }

    public Integer getFrom_type() {
        return from_type;
    }

    public void setFrom_type(Integer from_type) {
        this.from_type = from_type;
    }

    public String getTo_id() {
        return to_id;
    }

    public void setTo_id(String to_id) {
        this.to_id = to_id;
    }

    public Integer getMsg_type() {
        return msg_type;
    }

    public void setMsg_type(Integer msg_type) {
        this.msg_type = msg_type;
    }

    public Integer getMsg_status() {
        return msg_status;
    }

    public void setMsg_status(Integer msg_status) {
        this.msg_status = msg_status;
    }

    public String getMsg_content() {
        return msg_content;
    }

    public void setMsg_content(String msg_content) {
        this.msg_content = msg_content;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getWard_id() {
        return ward_id;
    }

    public void setWard_id(String ward_id) {
        this.ward_id = ward_id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
