package com.iAcon.database.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JIANHU.
 */
public class jianhu {

    private Long user_id;
    private String nick_name;
    private String status;

    public jianhu() {
    }

    public jianhu(long user_id) {
        this.user_id = user_id;
    }

    public jianhu(long user_id, String nick_name, String status) {
        this.user_id = user_id;
        this.nick_name = nick_name;
        this.status = status;
    }

    public long getUser_id() {
        return user_id;
    }

    public void setUser_id(long user_id) {
        this.user_id = user_id;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
